version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE=laravel
      MYSQL_USER=laravel
      MYSQL_PASSWORD=secret
      MYSQL_ROOT_PASSWORD=secret
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
